on: workflow_dispatch

jobs:
  run-ispw-deployment-list:
    runs-on: [self-hosted]
    name: A job to get deployment list of Code Pipeline
    steps:
      - name: Deployment List
        env: 
          CES_TOKEN: ${{ secrets.CES_TOKEN_KAJAL }}
        uses: bmc-compuware/code-pipeline-deployment-list@master
        id: deploymentlist
        with:
          ces_url: "http://172.19.173.36:48226/"
          ces_token: env.CES_TOKEN
          srid: "cw09"
          todaysDate: "false"
          priorWeek: "false"
          startDate: "2023-08-09"
          endDate: "2023-08-14"
          requestId: "245274"
          setId: "S000385216"
          environment: "PLAY"
          status: "Completed"
      
    
