on: workflow_dispatch

jobs:
  run-ispw-deployment-list:
    runs-on: [self-hosted]
    name: A job to get deployment list of Code Pipeline
    steps:
      - name: Deployment List
        uses: bmc-compuware/code-pipeline-deployment-list@master
        id: deploymentlist
        with:
          ces_url: "http://172.19.173.36:48226/"
          ces_token: "692ded79-f9c0-4e96-9f0a-109759fdc80a"
          srid: "cw09"
          todaysDate: "false"
          priorWeek: "false"
          startDate: "2023-08-09"
          endDate: "2023-10-14"
          environment: "PLAY"
          status: "Completed"
      
    
