on: workflow_dispatch

jobs:
  run-ispw-deployment-list:
    runs-on: [self-hosted]
    name: A job to get deployment list of Code Pipeline
    steps:
      - name: Deployment List
        uses: bmc-compuware-test/codepipeline-deployment-list@main
        id: deploymentlist
        with:
          ces_url: "http://172.19.173.207:48080/"
          ces_token: "a62dfc2d-da46-4905-871e-303a97bb6f32"
          srid: CW09
