
on: workflow_dispatch

jobs:
  run-ispw-generate:
    runs-on: [self-hosted]
    name: A job to generate source in Code Pipeline
    steps:
      - name: Generate
        uses: bmc-compuware/ispw-generate@feature/ZENG-438508-(1/2)-GitHub-Actions-need-to-have-ability-to-act-on-a-Container-for-Generate-action
        id: generate
        with:
          ces_url: "http://localhost:48080/"
          ces_token: "b9bbe27f-5ced-4b72-a39d-fd215d661626"
          srid: TPTP
          runtime_configuration: TPTP
          assignment_id: KATE012560
          level: DEV1
      - name: Get the set ID for the generate
        run: echo "The Code Pipeline set used for the generate is ${{ steps.generate.outputs.set_id }}"
