on: workflow_dispatch

jobs:
  run-ispw-generate:
    runs-on: [self-hosted]
    name: A job to generate source in Code Pipeline
    steps:
      - name: Generate
        uses: bmc-compuware/ispw-generate@v1
        id: generate
        with:
          ces_url: "http://172.19.173.207:48080/"
          ces_token: "a62dfc2d-da46-4905-871e-303a97bb6f32"
          srid: TPTP
          runtime_configuration: TPTP
          assignment_id: KATE012501
          level: DEV1
          task_id: "7E79E2C8ACE2,7E7A4B07B1C1"
      - name: Get the set ID for the generate
        run: echo "The Code Pipeline set used for the generate is ${{ steps.generate.outputs.set_id }}"
