# This is a basic workflow to help you get started with Actions

name: ispw sync local with certificate

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  github-ispw-sync:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      Win_Topaz_Location: 'C:\Jalaj\TopazISPW\InstalledApplication\TopazWorkBenchCLI20.15.1'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       -  name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
       -  name: Synchronize
          uses: bmc-compuware/ispw-sync-local@v1.3
          id: sync-local
          with:
            host: 'cw09.compuware.com'
            port: 47623            
            certificate: ${{ secrets.CERTIFICATE }}
            runtimeConfiguration: 'TPZP'
            stream: 'PLAY'
            application: 'PLAY'
            checkoutLevel: 'DEV1'
            gitUid: 'jarora8'
            gitToken: ${{ secrets.TOKEN_GITHUB }}
            winTopazPath: ${{ env.Win_Topaz_Location }}
            showEnv: true
