name: code-pipeline-sync-local

on: workflow_dispatch

jobs:
  generate:
    name: sync, build & deploy
    runs-on: self-hosted
    env:
      Win_Topaz_Location: 'C:\Jalaj\23.4CLI'
    
    steps:
      - name: checkout step
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: sync step
        uses: bmc-compuware/ispw-sync-local@main
        id: sync
        with:
          host: 'cw09.bmc.com'
          port: 47624
          uid: 'pinjxa0'
          pass: 'ispw18'
          runtimeConfiguration: 'TPTP'
          stream: 'TOPAZ'
          application: 'KATE'
          subAppl: 'KATE'
          checkoutLevel: 'DEV1'
          gitUid: 'jarora8'
          gitToken: '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'
          winTopazPath: ${{ env.Win_Topaz_Location }}
          #containerCreation: 'per-branch'
          showEnv: true
      
      - name: Get automatic build parameters
        run: echo "automaticBuildJson=${{ steps.sync.outputs.automaticBuildJson }}"
     
